eik-lib/cli

classes/alias.js
classes/init.js
classes/publish/app.js
classes/publish/dependency.js
classes/publish/map.js
classes/version.js
commands/alias.js
commands/dependency.js
commands/init.js
commands/map.js
commands/publish.js
commands/version.js
package.json
test/alias.test.js
test/init.test.js
test/publish.app.test.js
test/publish.dependency.test.js
test/publish.map.test.js
test/version.test.js
utils/logger.js
utils/send-command.js

I've lined up CLI with latest changes to server as well as tuned output so that its clear and minimal unless you pass a new `--debug` flag in which case you get all the logs.
Some caveats:
* alias `pkg` doesn't work (though alias `map` does) due to 404 from server
* tests won't pass until server memory sink is updated. See https://github.com/asset-pipe/core/pull/44
* tests wont pass until alias command works (see first point above)
* tests wont pass when run via tap. Ie. `tap test/*.test.js` does not pass though `node test/init.test.js` does. Need to look further but error is very confusing, missing server deps when run this way 🤷‍♂

Cli output improvements

---

classes/init.js
classes/meta.js
classes/publish/app.js
classes/publish/dependency.js
commands/meta.js
package.json
test/init.test.js
utils/logger.js

I noticed an issue where the node_modules in the temp dir had gotten corrupted or otherwise disturbed and it was no longer possible to get things working again without going into the temp folder and clearing things out manually so I thought it would be better to use a different random dir for each build and clean it up afterwards

make temp dir more random and delete after use

---

utils/send-command.js

Makes the client align with https://github.com/eik-lib/core/pull/62. This will probably break tests until core is published with the new field name.

Change form field for tar file to align with new name in core

---

package.json
test/alias.test.js
test/meta.test.js
test/publish.app.test.js
test/publish.dependency.test.js
test/publish.map.test.js
test/utils.js

I've copied the fastify service class from core and used it here as a function wrapper for tests. Not sure if we want to go down this path due to the (mostly) duplication of code. It might be quite useful for controlling test mocking and such down the road though.

add mock app service for tests

---

classes/publish/dependency.js
commands/dependency.js

This PR makes it possible to publish an npm dependency without specifying a version (which will then default to latest)
With this PR the following 2 examples are both valid
```sh
eik dependency lodash
```
```sh
eik dependency lodash 4.17.0
```

allow not specifying exact npm version for a dependency

---

classes/publish/npm.js
classes/publish/package/index.js
commands/map.js
commands/meta.js
commands/npm.js
commands/package.js
test/publish.npm.test.js
test/publish.package.test.js
utils/artifact.js
utils/index.js
utils/version.js

This PR aligns command output with some nice coloured formatting to match the formatting of the meta command
**Output for the package command:**
**Output for the import map command:**
**Output for the import npm command:**

Improve publish command output

---

classes/publish/package/index.js
commands/package.js
test/integration/package.test.js

* enforces the presence of an assets.json file in the CWD when using the package/publish command
* aliases package to publish so you can run eik publish
* removes command line arguments for map, js, css, name and server when running the package/publish command

Tweak package command2

---

.github/workflows/publish.yml
.github/workflows/test.yml
package.json
release.config.js
renovate.json

This adds semantic release making the process of curating a release, adding a change log and publishing to NPM fully automatic. No humans required.
Its worth noticing:
* This setup adhere to the [Angular flavor of Conventional Commit].(https://github.com/angular/angular/blob/22b96b9/CONTRIBUTING.md#-commit-message-guidelines). 
* Automatic releases is only cut on merge to master and is done through a github action. 
* All updates to dependencies by renovate bot will trigger an automatic release of this module if tests passes. 
* All updates to dev dependencies  by renovate bot will *NOT* trigger an automatic release of this module.
* When a new version is automatically released, semantic release will update package.json with the version number and commit it back to git.
Merging this PR …

Add semantic release

---

.github/workflows/test.yml
classes/publish/package/tasks/create-bundles.js
package.json
utils/calculate-file-hash.js
utils/calculate-files-hash.js

result.map is an object instance with a toString that produces a source map. This stringification used to happen automatically in node 13 and earlier. In node 14 it throws when it doesn't actually get a string so it is now necessary to first stringify the object before passing it to writeFileSync.

fix: convert object to string for writeFileSync

---

classes/publish/package/index.js

Dry run files were being cleaned up which meant there was no way to inspect produced files. This stops clean up for dry runs

fix: do not cleanup tmp files on dry run

---

.gitignore
classes/publish/package/index.js
classes/publish/package/tasks/check-bundle-sizes.js
classes/publish/package/tasks/check-if-already-published.js
classes/publish/package/tasks/create-zip-file.js
classes/publish/package/tasks/dry-run.js
classes/publish/package/tasks/validate-input.js
classes/version.js
commands/init.js
commands/package.js
commands/version.js
test/alias.test.js
test/integration/alias.test.js
test/integration/init.test.js
test/integration/integrity.test.js
test/integration/package.test.js
test/integration/react/react.test.js
test/integrity.test.js
test/publish.package.test.js
test/utils.test.js
utils/files.js
utils/get-defaults.js
utils/index.js

As per suggestion from @stipsan I've renamed `entrypoints` to `files` in `eik.json`

fix: rename entrypoints to files

---

commands/init.js
test/integration/init.test.js

Thought I had fixed this. Major is from the early days of Eik, we don't use it any more.
Fixes #178

fix: remove major field, replace with version in init command

---

classes/index.js
classes/version.js
test/version.test.js

Version command was not exposed publicly, and had no tests. This PR fixes those 2 issues.
In addition, the ValidationError class in `@eik/common` was being incorrectly referenced in the Version command so that is fixed as well

fix: expose version, fix ValidationError usage, add tests

---

classes/alias.js
commands/package-alias.js

Sets the name, version and alias values from eik.json if not provided in the command itself.
This should make it easier to run the command on CI

feat: auto detect and set values when performing package aliasing

---

commands/package.js
commands/version.js
test/integration/package.test.js
utils/get-defaults.js

This PR makes it possible to specify Eik values using `package.json`
The package.json `name` and `version` fields are used for the Eik `name` and `version` values. All other values are specified using an `eik` key.
For example
```json
{
"name": "test-app",
"version": "1.0.0",
"eik": { }
}
```
The `eik` key can be used to specify any other fields that are accepted by `eik.json`.
If an `eik.json` file is also present, values will be merged with `eik.json` winning in the case of a clash.

Support eik in package json

---

package.json
release.config.js

This ads a semantic release plugin to ping a slack channel for when a new release of the client is cut.

ci: Add semantic release slack integration

---

classes/publish/package/index.js
classes/publish/package/tasks/save-metafile.js
classes/publish/package/tasks/upload-files.js

Currently there is a miss match between the integrity file stored when running the `publish` and `integrity` command. When a `publish` is run, the stored integrity file in the `./eik` folder looks like this:
```json
{
"version": "1.0.0",
"integrity": "sha512-I5dyMaKAWNG91Ncl+q00+4fiPT0+DOhQmf+TH6oVuDy7ZnkkPSGYDSRWBhLj+KS4uafFGgBDvXJqQzVXs+hjZA=="
}
```
When the `integrity` command is run the same file looks like his:
```json
{
"name": "@finn-no/trygve-lit-test",
"version": "1.0.0",
"integrity": "sha512-I5dyMaKAWNG91Ncl+q00+4fiPT0+DOhQmf+TH6oVuDy7ZnkkPSGYDSRWBhLj+KS4uafFGgBDvXJqQzVXs+hjZA==",
"files": {
"/eik.json": "sha512-zHQjnDpMW7IKVyTpT9cOPT1+xhUSOcbgXj6qHCPSPu1CbQfgwDEsIniXU54zDIN71zqmxLSp3hfIljpt69ok0w==",
"/lit-element.js": …
```

fix: Standardize stored integrity file between publish and integrity command

---

classes/publish/package/index.js

Why: Its frustrating to try to publish a new version you have explicitly set and have it fail because the system determines that the files are the same as the previous version.

fix: remove restrictions to publishing when files are same as previous version

---

release.config.js

Currently there is a difference in the slack boot messages for pre-releases and releases on main. Slim these down.

ci: Slim down slack bot messages for pre-releases

---

.prettierignore
classes/alias.js
commands/login.js
renovate.json
test/integration/package.test.js

@leftieFriele and I spent a little while figuring out why the CLI couldn't find our NPM package, which turns out was published as a regular application package. In other words our `eik npm-alias` needed to be `eik package-alias`.

Debug logs

---

classes/publish/package/tasks/upload-files.js

Sometimes asset uploads fails with error messages: 
`Error: Error: Server failed`
`Error: Error: Server was unable to write file to storage`
We need some more information about status code and message from the response to debug this.

better error messages on server upload

---

commands/alias.js
commands/index.js
commands/init.js
commands/login.js
commands/map-alias.js
commands/map.js
commands/meta.js
commands/npm-alias.js
commands/publish.js
test/integration/alias-legacy.test.mjs

This is a non breaking change but does add deprecation messages for pkg-alias, map-alias and npm-alias, all of which are replaced by this new alias command.
The alias command detects type from eik.json which was not possible in earlier versions of the cli which was the reason for the existence of 3 separate commands instead of 1. If the command is run in a directory that does not contain an eik.json file, type can be provided via the command line argument --type. If neither are present, an error is thrown.
There is some formatting of command messages thrown in for good measure with this PR.

feat: add alias command as an eventual replacement for the 3 existing alias commands
